// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc7z8loef4mENPitfd2C1HXv6oSWU87b4',
    appId: '1:127376482692:web:2ebee8d85c0dea23663dd1',
    messagingSenderId: '127376482692',
    projectId: 'sholar-chat-2',
    authDomain: 'sholar-chat-2.firebaseapp.com',
    storageBucket: 'sholar-chat-2.firebasestorage.app',
    measurementId: 'G-CY61TG941S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz1ZsYRKb89ipq9Qb-sUA28QmOye9jjB4',
    appId: '1:127376482692:android:67567d0b32fd570b663dd1',
    messagingSenderId: '127376482692',
    projectId: 'sholar-chat-2',
    storageBucket: 'sholar-chat-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRsE17V4pWvsty8r3f19LWQCEVSEd0Pfw',
    appId: '1:127376482692:ios:f26414a58f2acee9663dd1',
    messagingSenderId: '127376482692',
    projectId: 'sholar-chat-2',
    storageBucket: 'sholar-chat-2.firebasestorage.app',
    iosClientId: '127376482692-1iaonltabn69cj81grt0sdddddmfiao6.apps.googleusercontent.com',
    iosBundleId: 'com.gomaa.zenith.zenithApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRsE17V4pWvsty8r3f19LWQCEVSEd0Pfw',
    appId: '1:127376482692:ios:f26414a58f2acee9663dd1',
    messagingSenderId: '127376482692',
    projectId: 'sholar-chat-2',
    storageBucket: 'sholar-chat-2.firebasestorage.app',
    iosClientId: '127376482692-1iaonltabn69cj81grt0sdddddmfiao6.apps.googleusercontent.com',
    iosBundleId: 'com.gomaa.zenith.zenithApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO7eYltxHacoETnhFQHIolslvNMCddoGQ',
    appId: '1:127376482692:web:dc47e3819a8135f6663dd1',
    messagingSenderId: '127376482692',
    projectId: 'sholar-chat-2',
    authDomain: 'sholar-chat-2.firebaseapp.com',
    storageBucket: 'sholar-chat-2.firebasestorage.app',
    measurementId: 'G-88K2VBQE3K',
  );
}
